# Generated by Django 6.0.4 on 2026-06-08 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(max_length=64)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='chat.interviewsession')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
