# Generated by Django 6.0.4 on 2026-06-15 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('target_role', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('writer_done', 'Writer concluído'), ('reviewer_done', 'Reviewer concluído'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='generating', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='chat.interviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('html_rendered', models.TextField(blank=True, default='')),
                ('generated_by_agent', models.CharField(max_length=32)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'ordering': ['resume_id', 'version_number'],
                'unique_together': {('resume', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall', models.DecimalField(decimal_places=2, max_digits=4)),
                ('criteria', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=list)),
                ('resume_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='resumes.resumeversion')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
