# Generated by Django 6.0.4 on 2026-06-17 22:02

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='structured_data_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
