# Generated by Django 6.0.4 on 2026-06-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_k_categor_4c1c4e_idx',
            old_name='knowledge_k_categor_4be20a_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_k_priorit_06ceec_idx',
            old_name='knowledge_k_priorit_a78bd0_idx',
        ),
    ]
