#!/usr/bin/env uv run python
"""Generate Codex custom-agent TOML files from Claude agent markdown files."""

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


FRONTMATTER_RE = re.compile(r"\A---\n(?P<meta>.*?)\n---\n(?P<body>.*)\Z", re.DOTALL)


@dataclass(frozen=True)
class ClaudeAgent:
    source_path: Path
    source_label: str
    name: str
    description: str
    body: str


def parse_simple_frontmatter(
    markdown: str,
    source_path: Path,
    *,
    source_label: str,
) -> ClaudeAgent:
    match = FRONTMATTER_RE.match(markdown)
    if not match:
        raise ValueError(f"Missing frontmatter: {source_path}")

    metadata: dict[str, str] = {}
    for raw_line in match.group("meta").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip().strip('"').strip("'")

    name = metadata.get("name")
    description = metadata.get("description")
    if not name or not description:
        raise ValueError(f"Missing name or description in {source_path}")

    return ClaudeAgent(
        source_path=source_path,
        source_label=source_label,
        name=name,
        description=description,
        body=match.group("body").strip(),
    )


def toml_string(value: str) -> str:
    return '"""' + value.replace('"""', '\\"\\"\\"') + '"""'


def render_codex_agent(agent: ClaudeAgent) -> str:
    instructions = agent.body

    return "\n".join(
        [
            "# Generated by scripts/sync_codex_agents.py. Do not edit by hand.",
            f"# Source: {agent.source_label}",
            f"name = {toml_string(agent.name)}",
            f"description = {toml_string(agent.description)}",
            f"developer_instructions = {toml_string(instructions)}",
            "",
        ]
    )


def iter_claude_agents(source_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in source_dir.glob("*.md")
        if path.name not in {"CLAUDE.md", "AGENTS.md"} and path.is_file()
    )


def sync_agents(source_dir: Path, output_dir: Path, *, dry_run: bool) -> list[str]:
    messages: list[str] = []
    agent_paths = iter_claude_agents(source_dir)

    if not agent_paths:
        return [f"No agent markdown files found in {source_dir}"]

    if not dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    for agent_path in agent_paths:
        source_label = agent_path.relative_to(source_dir.parent.parent).as_posix()
        agent = parse_simple_frontmatter(
            agent_path.read_text(),
            agent_path,
            source_label=source_label,
        )
        output_path = output_dir / f"{agent.name}.toml"
        rendered = render_codex_agent(agent)

        if output_path.exists() and output_path.read_text() == rendered:
            messages.append(f"ok      {output_path}")
            continue

        action = "update" if output_path.exists() else "create"
        if not dry_run:
            output_path.write_text(rendered)
        messages.append(f"{action:<7} {output_path}")

    return messages


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate .codex/agents/*.toml from .claude/agents/*.md. "
            "Keeps the Claude markdown definitions as the canonical source."
        )
    )
    parser.add_argument(
        "root",
        nargs="?",
        default=".",
        help="Repo root. Defaults to the current directory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned changes without writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(args.root).expanduser().resolve()
    source_dir = root / ".claude" / "agents"
    output_dir = root / ".codex" / "agents"

    if not source_dir.is_dir():
        print(f"Source directory not found: {source_dir}")
        return 2

    for message in sync_agents(source_dir, output_dir, dry_run=args.dry_run):
        print(message)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
