# Generated by Django 6.0.4 on 2026-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_candidate_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='base_photo',
            field=models.ImageField(blank=True, null=True, upload_to='base-photos/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo_status',
            field=models.CharField(choices=[('idle', 'idle'), ('generating', 'generating'), ('ready', 'ready'), ('failed', 'failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='professional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='professional-photos/'),
        ),
    ]
