# Generated by Django 6.0.4 on 2026-06-08 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída')], default='active', max_length=16)),
                ('current_phase', models.CharField(choices=[('intro', 'Introdução'), ('personal_info', 'Dados pessoais'), ('education', 'Educação'), ('experience', 'Experiência'), ('projects', 'Projetos'), ('skills', 'Habilidades'), ('review', 'Revisão'), ('done', 'Finalizado')], default='intro', max_length=20)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=16)),
                ('content', models.JSONField(default=list)),
                ('is_visible', models.BooleanField(default=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.interviewsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
