# Generated by Django 6.0.4 on 2026-04-29 15:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('expected_status', models.PositiveSmallIntegerField(default=200, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(599)])),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('unknown', 'Desconhecido'), ('ok', 'OK'), ('fail', 'Falhou')], default='unknown', max_length=10)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
